language: python
python: 2.7
sudo: false
cache:
  directories:
  - eggs
  - parts/node
addons:
  firefox: latest-esr
env:
- PLONE_VERSION=4.3 VERSIONS=versions:plone.app.registry=1.5
- PLONE_VERSION=5.0
- PLONE_VERSION=5.1
matrix:
  fast_finish: true
before_install:
before_install:
# FIXME: I have no idea how and why six==1.11.0 is being installed
- pip uninstall -y six
install:
- sed -ie "s#test-4.3#test-$PLONE_VERSION#" buildout.cfg
- python bootstrap.py
- bin/buildout $VERSIONS annotate
- bin/buildout $VERSIONS
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- firefox -v
script:
- bin/code-analysis
- bin/test
- bin/pylint --py3k --disable=no-absolute-import src/collective/lazysizes
after_success:
- bin/createcoverage --output-dir=htmlcov -t "--layer=!Robot"
- pip install coveralls
- coveralls
notifications:
  irc: irc.freenode.org#plone-testing
